name: Trigger Swarm

on:
  issues:
    types: [labeled]

jobs:
  trigger:
    if: github.event.label.name == 'ready-to-build'
    runs-on: ubuntu-latest
    steps:
      - name: Notify VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          echo "$VPS_SSH_KEY" > /tmp/vps_key
          chmod 600 /tmp/vps_key

          ssh -o StrictHostKeyChecking=no -i /tmp/vps_key deploy@$VPS_HOST \
            "/opt/swarm-platform/trigger.sh ${{ github.repository }} ${{ github.event.issue.number }}"

          rm /tmp/vps_key
